language: node_js
node_js:
  - "10"
cache:
 apt: true
 directories:
   - node_modules
branches:
  only:
    - gitpages

before_install:
  - export TZ='Asia/Tokyo'
  - npm install -g hexo-cli hexo-renderer-scss hexo-filter-responsive-images imageinfo js-yaml

install:
  - npm install
  - npm install hexo-deployer-git save

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "kuritan"
  - git config user.email "yujia.zhai@hotmail.com"
  - sed -i "s/gh_token/${GIT}/g" ./_config.yml
  - hexo deploy

